# Generated by Django 5.0.4 on 2024-05-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_rename_created_watchlist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
